export const formSchema = [
  {
    label: "Surname",
    name: "surname",
    type: "text",
    required: true,
    placeholder: "Enter surname",
    className: "w-50 p-1",
  },
  {
    label: "Given Name",
    name: "givenN",
    type: "text",
    required: true,
    placeholder: "Enter given name",
    className: "w-50 p-1",
  },
  {
    label: "Email",
    name: "email",
    type: "email",
    required: true,
    placeholder: "Enter email",
    className: "w-100 p-1",
  },
  {
    label: "Phone",
    name: "phone",
    type: "text",
    required: true,
    placeholder: "Enter phone number",
    className: "w-50 p-1",
  },
  {
    label: "National ID",
    name: "nationalId",
    type: "text",
    required: true,
    placeholder: "Enter national ID",
    className: "w-50 p-1",
  },
  {
    label: "Sex",
    name: "sex",
    type: "select",
    required: true,
    options: ["Male", "Female"],
    className: "w-50 p-1",
  },
  {
    label: "Date of Birth",
    name: "dob",
    type: "date",
    required: true,
    className: "w-50 p-1",
  },
  {
    label: "Place of Birth Town/City",
    name: "birthCity",
    type: "text",
    required: true,
    placeholder: "Enter birth city",
    className: "w-50 p-1",
  },
  {
    label: "Current Nationality",
    name: "currentN",
    type: "text",
    required: true,
    placeholder: "Enter current nationality",
    className: "w-50 p-1",
  },
  {
    label: "Identification Marks",
    name: "identification",
    type: "text",
    required: true,
    placeholder: "Enter identification marks",
    className: "w-100 p-1",
  },
  {
    label: "Company Name",
    name: "company",
    type: "text",
    required: true,
    placeholder: "Enter company name",
    className: "w-50 p-1",
  },
  {
    label: "Duty Duration",
    name: "dutyDuration",
    type: "text",
    value: "8 Hours",
    required: true,
    className: "w-50 p-1",
  },
  {
    label: "Job Title",
    name: "jobTitle",
    type: "select",
    required: true,
    options: [
      "Driving",
      "Packing",
      "Construction",
      "Electrician",
      "Holder",
      "Housekeeping",
      "Cleaner",
      "Plumber",
      "Packaging",
      "Cook",
      "Restaurant",
      "Manager",
      "Supervisor",
      "Worker",
      "Caring Operator",
    ],
    className: "w-50 p-1",
  },
  {
    label: "Salary",
    name: "salary",
    type: "text",
    required: true,
    placeholder: "Enter salary",
    className: "w-50 p-1",
  },
  {
    label: "Image",
    name: "image",
    type: "file",
    required: true,
    accept: "image/*",
    className: "w-100 p-1",
  },
  {
    label: "Passport",
    name: "passport",
    type: "text",
    required: true,
    placeholder: "Enter passport number",
    className: "w-100 p-1",
  },
  {
    label: "Issued Country",
    name: "issuedCountry",
    type: "text",
    required: true,
    placeholder: "Enter issued country",
    className: "w-100 p-1",
  },
];
